extern const GeoLayout bob_area_1_geo[];
extern const GeoLayout bob_area_1[];
extern const Collision bob_area_1_collision[];
extern const MacroObject bob_area_1_macro_objs[];
extern u8 bob_dl_stripes1_i8[];
extern u8 bob_dl_Pic__40__i8[];
extern u8 bob_dl_Pic__97__rgba16[];
extern u8 bob_dl_MARIOKART64_103A1EEE_0_2_all_rgba16[];
extern u8 bob_dl_Pic__100__rgba16[];
extern u8 bob_dl_water_rgba16[];
extern Vtx bob_dl_Cylinder_mesh_layer_1_vtx_cull[8];
extern Vtx bob_dl_Cylinder_mesh_layer_1_vtx_0[304];
extern Gfx bob_dl_Cylinder_mesh_layer_1_tri_0[];
extern Vtx bob_dl_Plane_mesh_layer_1_vtx_cull[8];
extern Vtx bob_dl_Plane_mesh_layer_1_vtx_0[59];
extern Gfx bob_dl_Plane_mesh_layer_1_tri_0[];
extern Vtx bob_dl_Plane_mesh_layer_1_vtx_1[573];
extern Gfx bob_dl_Plane_mesh_layer_1_tri_1[];
extern Vtx bob_dl_Plane_001_mesh_layer_4_vtx_cull[8];
extern Vtx bob_dl_Plane_001_mesh_layer_4_vtx_0[12];
extern Gfx bob_dl_Plane_001_mesh_layer_4_tri_0[];
extern Vtx bob_dl_Plane_003_mesh_layer_1_vtx_cull[8];
extern Vtx bob_dl_Plane_003_mesh_layer_1_vtx_0[102];
extern Gfx bob_dl_Plane_003_mesh_layer_1_tri_0[];
extern Vtx bob_dl_Water_Box_Mesh_mesh_layer_5_vtx_cull[8];
extern Vtx bob_dl_Water_Box_Mesh_mesh_layer_5_vtx_0[114];
extern Gfx bob_dl_Water_Box_Mesh_mesh_layer_5_tri_0[];
extern Gfx mat_bob_dl_f3dlite_material_001[];
extern Gfx mat_revert_bob_dl_f3dlite_material_001[];
extern Gfx mat_bob_dl_purple_juice[];
extern Gfx mat_revert_bob_dl_purple_juice[];
extern Gfx mat_bob_dl_stone[];
extern Gfx mat_revert_bob_dl_stone[];
extern Gfx mat_bob_dl_gate[];
extern Gfx mat_revert_bob_dl_gate[];
extern Gfx mat_bob_dl_slipstone[];
extern Gfx mat_revert_bob_dl_slipstone[];
extern Gfx mat_bob_dl_sm64_water_mat[];
extern Gfx mat_revert_bob_dl_sm64_water_mat[];
extern Gfx bob_dl_Cylinder_mesh_layer_1[];
extern Gfx bob_dl_Plane_mesh_layer_1[];
extern Gfx bob_dl_Plane_001_mesh_layer_4[];
extern Gfx bob_dl_Plane_003_mesh_layer_1[];
extern Gfx bob_dl_Water_Box_Mesh_mesh_layer_5[];
