extern const GeoLayout bob_area_1_geo[];
extern const GeoLayout bob_area_1[];
extern const Collision bob_area_1_collision[];
extern const MacroObject bob_area_1_macro_objs[];
extern u8 bob_dl_stripes1_i8[];
extern u8 bob_dl_Pic__40__i8[];
extern u8 bob_dl_Pic__97__ci8[];
extern u8 bob_dl_Pic__97__pal_rgba16[];
extern Vtx bob_dl_Cylinder_mesh_layer_1_vtx_cull[8];
extern Vtx bob_dl_Cylinder_mesh_layer_1_vtx_0[52];
extern Gfx bob_dl_Cylinder_mesh_layer_1_tri_0[];
extern Vtx bob_dl_Plane_mesh_layer_1_vtx_cull[8];
extern Vtx bob_dl_Plane_mesh_layer_1_vtx_0[60];
extern Gfx bob_dl_Plane_mesh_layer_1_tri_0[];
extern Vtx bob_dl_Plane_mesh_layer_1_vtx_1[266];
extern Gfx bob_dl_Plane_mesh_layer_1_tri_1[];
extern Gfx mat_bob_dl_f3dlite_material_001[];
extern Gfx mat_revert_bob_dl_f3dlite_material_001[];
extern Gfx mat_bob_dl_purple_juice[];
extern Gfx mat_revert_bob_dl_purple_juice[];
extern Gfx mat_bob_dl_stone[];
extern Gfx mat_revert_bob_dl_stone[];
extern Gfx bob_dl_Cylinder_mesh_layer_1[];
extern Gfx bob_dl_Plane_mesh_layer_1[];
